namespace Pexeso.Game.ContentProviders;

public class CzechContentProvider : IContentProvider {
    // This is generated by ChatGPT for the most part
    private string[] content = {
        "Krteček", "Hurvínek", "Cimrman", "Švejk", "Rákosníček", "Rumcajs", "Jiří Ovčáček", "Mariáš", "Matfyz", "Kolohousenka",
        "Červená karkulka", "Vodník", "Čert", "Drak", "Bílá paní", "Golem", "Ježibaba", "Krakonoš", "Kocour Mikeš", "Večerníček",
        "Housle", "Cimbál", "Fujara", "Harmonikář", "Trumpeta", "Saxofon", "Tamburína", "Dudy", "Klávesy", "Flétna",
        "Pohádka", "Dobrodružství", "Poklad", "Záhada", "Skřítek", "Lesní víla", "Labuť", "Sokol", "Ledňáček", "Jezevec",
        "Borůvka", "Malina", "Jablko", "Švestka", "Hruška", "Třešeň", "Višeň", "Meruňka", "Meloun", "Rakytník",
        "Hokej", "Fotbal", "Florbal", "Lyžování", "Biatlon", "Kanoistika", "Lezení", "Plavání", "Šachy", "Atletika",
        "Knihovna", "Zámek", "Hrad", "Radnice", "Staromák", "Karlův most", "Vyšehrad", "Petřín", "Pražský hrad", "Orloj",
        "Houska", "Chléb", "Rohlík", "Koláč", "Trdelník", "Kobliha", "Medovník", "Bábovka", "Svíčková", "Guláš",
        "Kolo", "Motorka", "Lokomotiva", "Vespa", "Plachetnice", "Vzducholoď", "Balón", "Tramvaj", "Trolejbus", "Kabriolet",
        "Sluníčko", "Měsíc", "Hvězda", "Planeta", "Kometa", "Meteor", "Polární záře", "Duhový most", "Paprsek", "Bouřka"
    };

    public Pair[] GetPairs(int number) {
        string[] shuffled = (string[]) content.Clone();
        shuffled.Shuffle();
        Pair[] pairs = new Pair[number];
        int contentIndex = 0;
        for (int i = 0; i < number; i++) {
            pairs[i] = new Pair(content[i], content[i]);
            contentIndex++;
        }
        return pairs;
    }
}