namespace Pexeso.Game.ContentProviders;

using System;

public class DefaultContentProvider : IContentProvider {
    // This is generated by ChatGPT for the most part
    private readonly string[] content = {
        "Apple", "Tree", "Linear Algebra", "Isaac Newton", "Whiteboard", "Marriage", "Computer", "Linux", "Windows",
        "John Smith", "Astrology", "Capricorn", "Wololo", "Cuphead", "Hash Function", "Functional Programming", "Disfunctional Programming",
        "Batman", "Sherlock", "Gandalf", "Yoda", "Mario", "Luffy", "Dumbledore", "Frodo", "Spock", "Thor",
        "Excalibur", "TARDIS", "Mjolnir", "Ecto-1", "DeLorean", "Infinity Gauntlet", "One Ring", "Lightsaber", "Hoverboard", "Stormbreaker",
        "Phoenix", "Kraken", "Chimera", "Griffin", "Cerberus", "Pegasus", "Bigfoot", "Loch Ness", "Werewolf", "Dragon",
        "Astronaut", "Pirate", "Knight", "Ninja", "Samurai", "Viking", "Detective", "Wizard", "Alien", "Robot",
        "Popcorn", "Banana", "Chocolate", "Cupcake", "Marshmallow", "Cheeseburger", "Taco", "Sushi", "Pineapple", "Strawberry",
        "Rainbow", "Moonlight", "Sunflower", "Bubblegum", "Waterfall", "Snowflake", "Thunderstorm", "Volcano", "Tornado", "Glacier",
        "Echo", "Whisper", "Boomerang", "Zebra", "Cactus", "Hedgehog", "Koala", "Panda", "Octopus", "Chameleon",
        "Magic", "Illusion", "Puzzle", "Adventure", "Treasure", "Labyrinth", "Enigma", "Mystery", "Quest", "Secret",
        "Shadow", "Eclipse", "Starlight", "Nebula", "Meteor", "Comet", "Aurora", "Cosmos", "Galaxy", "Supernova",
        "Captain", "Jester", "Explorer", "Gladiator", "Juggler", "Sorcerer", "Time Traveler", "Alchemist", "Inventor", "Dreamer"
    };

    public Pair[] GetPairs(int number) {
        number = Math.Min(number, content.Length);
        string[] shuffled = (string[]) content.Clone();
        shuffled.Shuffle();
        Pair[] pairs = new Pair[number];
        int contentIndex = 0;
        for (int i = 0; i < number; i++) {
            pairs[i] = new Pair(content[i], content[i]);
            contentIndex++;
        }
        return pairs;
    }

    public bool IsGraphic() {
        return false;
    }
}